[project]
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "flow-experiment"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"


[dependencies]
python = "~=3.12"
arviz = ">=0.18.0"
graphviz = "*"
jupyterlab = ">=4.2"
jax = "~=0.4.31"
numba = ">=0.60"
numpy = "<=2.0"
pandas = ">=2.1"
polars = ">=1.1.0"
pyprojroot = ">=0.3.0"
scipy = ">=1.13.0"
seaborn = ">=0.13.0"
#numpyro = ">=0.15.0"
pytest = ">=8.2"
threadpoolctl = ">=3.5.0,<3.6"
python-graphviz = "*"
pytensor = ">=2.22.1"
blackjax = ">=1.2.0"
pymc = ">=5.16.2"
nutpie = ">=0.13.1"
ipykernel = ">=6.29.5,<7"
beartype = ">=0.19.0,<0.20"

[target.osx.dependencies]
libblas = { version = "*", build = "*accelerate" }

[target.linux-64.dependencies]
libblas = { version = "*", build = "*mkl" }

# [pypi-dependencies]
# Install the local directory editable
# name-of-project = { path = ".", editable = true }

[activation]
# Prevent jax from preallocating most of the GPU to avoid
# OOM conditions with multiple clients running concurrently
env = { XLA_PYTHON_CLIENT_PREALLOCATE = "false" }

[feature.cuda12]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }

[feature.cuda12.dependencies]
jaxlib = { version = "*", build = "*cuda12*" }
cuda-version = "12.*"

[environments]
default = { features = ["cuda12"] }
cuda12 = { features = ["cuda12"] }

[tasks]
jupyterlab = { cmd = "jupyter lab --no-browser" }
list-jax-devices = { cmd = "python -c 'import jax; print(jax.devices())'" }
test = { cmd = "pytest" }

[pypi-dependencies]
flowjax = { path = "./deps/flowjax", editable = true }
flowMC = { path = "./deps/flowMC", editable = true }
#optax = { path = "deps/optax", editable = true }
optax = "~=0.2.2"
perpetual = ">=0.4.12, <0.5"
